//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Classlibraraydata
{
    using System;
    using System.Collections.Generic;
    
    public partial class image_tbl
    {
        public int image_id { get; set; }
        public string image_name { get; set; }
        public byte[] image { get; set; }
        public string image_description { get; set; }
    }
}
